# Generated by Django 3.0.8 on 2020-08-01 12:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='posted',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
