# Generated by Django 3.0.8 on 2020-08-01 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_note_posted'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='posted',
            new_name='posted_on',
        ),
    ]
